sudo: required
services:
    - docker

before_install:
    - docker build -t mydockerid/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run mydockerid/react-test npm test -- --coverage

after_success:
    - docker build -t mydockerid/multi-client ./client
    - docker build -t mydockerid/multi-nginx ./nginx
    - docker build -t mydockerid/multi-server ./server
    - docker build -t mydockerid/multi-worker ./worker